export default [
  // i-adjectives
  { character: 'おおきい', sound: 'big', romaji: 'ookii' },
  { character: 'ちいさい', sound: 'small', romaji: 'chiisai' },
  { character: 'いい', sound: 'good', romaji: 'ii' },
  { character: 'わるい', sound: 'bad', romaji: 'warui' },
  { character: 'すごい', sound: 'great', romaji: 'sugoi' },
  { character: 'あたらしい', sound: 'new', romaji: 'atarashii' },
  { character: 'ふるい', sound: 'old', romaji: 'furui' },
  { character: 'さむい', sound: 'cold', romaji: 'samui' },
  { character: 'あつい', sound: 'hot', romaji: 'atsui' },
  { character: 'かっこいい', sound: 'cool', romaji: 'kakkoii' },
  { character: 'たかい', sound: 'expensive', romaji: 'takai' },
  { character: 'やすい', sound: 'cheap', romaji: 'yasui' },
  { character: 'きたない', sound: 'dirty', romaji: 'kitanai' },
  { character: 'たのしい', sound: 'fun', romaji: 'tanoshii' },
  { character: 'つまらない', sound: 'boring', romaji: 'tsumaranai' },
  { character: 'やさしい', sound: 'easy', romaji: 'yasashii' },
  { character: 'むずかしい', sound: 'dificult', romaji: 'muzukashii' },
  { character: 'おもしろい', sound: 'interesting', romaji: 'omoshiroi' },
  { character: 'いそがしい', sound: 'busy', romaji: 'isogashii' },
  { character: 'こわい', sound: 'scary', romaji: 'kowai' },

  // na-adjectives
  { character: 'きれい(な)', sound: 'pretty', romaji: 'kirei' },
  { character: 'しずか(な)', sound: 'quiet', romaji: 'shizuka' },
  { character: 'にぎやか(な)', sound: 'lively', romaji: 'nigiyaka' },
  { character: 'げんき(な)', sound: 'happy', romaji: 'genki' },
  { character: 'すき(な)', sound: 'like', romaji: 'suki' },
  { character: 'きらい(な)', sound: 'dislike', romaji: 'kirai' },
  { character: 'ひま(な)', sound: 'free', romaji: 'hima' },
];
