import ROWS from "./rows";

export default [
  { romaji: "a", character: "あ", row: ROWS.A },
  { romaji: "i", character: "い", row: ROWS.A },
  { romaji: "u", character: "う", row: ROWS.A },
  { romaji: "e", character: "え", row: ROWS.A },
  { romaji: "o", character: "お", row: ROWS.A },

  { romaji: "ka", character: "か", row: ROWS.KA },
  { romaji: "ki", character: "き", row: ROWS.KA },
  { romaji: "ku", character: "く", row: ROWS.KA },
  { romaji: "ke", character: "け", row: ROWS.KA },
  { romaji: "ko", character: "こ", row: ROWS.KA },

  { romaji: "sa", character: "さ", row: ROWS.SA },
  { romaji: "shi", character: "し", row: ROWS.SA },
  { romaji: "su", character: "す", row: ROWS.SA },
  { romaji: "se", character: "せ", row: ROWS.SA },
  { romaji: "so", character: "そ", row: ROWS.SA },

  { romaji: "ta", character: "た", row: ROWS.TA },
  { romaji: "chi", character: "ち", row: ROWS.TA },
  { romaji: "tsu", character: "つ", row: ROWS.TA },
  { romaji: "te", character: "て", row: ROWS.TA },
  { romaji: "to", character: "と", row: ROWS.TA },

  { romaji: "na", character: "な", row: ROWS.NA },
  { romaji: "ni", character: "に", row: ROWS.NA },
  { romaji: "nu", character: "ぬ", row: ROWS.NA },
  { romaji: "ne", character: "ね", row: ROWS.NA },
  { romaji: "no", character: "の", row: ROWS.NA },

  { romaji: "ha", character: "は", row: ROWS.HA },
  { romaji: "hi", character: "ひ", row: ROWS.HA },
  { romaji: "fu", character: "ふ", row: ROWS.HA },
  { romaji: "he", character: "へ", row: ROWS.HA },
  { romaji: "ho", character: "ほ", row: ROWS.HA },

  { romaji: "ma", character: "ま", row: ROWS.MA },
  { romaji: "mi", character: "み", row: ROWS.MA },
  { romaji: "mu", character: "む", row: ROWS.MA },
  { romaji: "me", character: "め", row: ROWS.MA },
  { romaji: "mo", character: "も", row: ROWS.MA },

  { romaji: "ra", character: "ら", row: ROWS.RA },
  { romaji: "ri", character: "り", row: ROWS.RA },
  { romaji: "ru", character: "る", row: ROWS.RA },
  { romaji: "re", character: "れ", row: ROWS.RA },
  { romaji: "ro", character: "ろ", row: ROWS.RA },

  { romaji: "ya", character: "や", row: ROWS.YA },
  { romaji: "yu", character: "ゆ", row: ROWS.YA },
  { romaji: "yo", character: "よ", row: ROWS.YA },

  { romaji: "wa", character: "わ", row: ROWS.WA },
  { romaji: "wo", character: "を", row: ROWS.WA },
  { romaji: "n", character: "ん", row: ROWS.WA },

  { romaji: "ga", character: "が", row: ROWS.ALT },
  { romaji: "gi", character: "ぎ", row: ROWS.ALT },
  { romaji: "gu", character: "ぐ", row: ROWS.ALT },
  { romaji: "ge", character: "げ", row: ROWS.ALT },
  { romaji: "go", character: "ご", row: ROWS.ALT },
  { romaji: "za", character: "ざ", row: ROWS.ALT },
  { romaji: "ji", character: "じ", row: ROWS.ALT },
  { romaji: "zu", character: "ず", row: ROWS.ALT },
  { romaji: "ze", character: "ぜ", row: ROWS.ALT },
  { romaji: "zo", character: "ぞ", row: ROWS.ALT },
  { romaji: "da", character: "だ", row: ROWS.ALT },
  { romaji: "ji", character: "ぢ", row: ROWS.ALT },
  { romaji: "zu", character: "づ", row: ROWS.ALT },
  { romaji: "de", character: "で", row: ROWS.ALT },
  { romaji: "do", character: "ど", row: ROWS.ALT },
  { romaji: "ba", character: "ば", row: ROWS.ALT },
  { romaji: "bi", character: "び", row: ROWS.ALT },
  { romaji: "bu", character: "ぶ", row: ROWS.ALT },
  { romaji: "be", character: "べ", row: ROWS.ALT },
  { romaji: "bo", character: "ぼ", row: ROWS.ALT },
  { romaji: "pa", character: "ぱ", row: ROWS.ALT },
  { romaji: "pi", character: "ぴ", row: ROWS.ALT },
  { romaji: "pu", character: "ぷ", row: ROWS.ALT },
  { romaji: "pe", character: "ぺ", row: ROWS.ALT },
  { romaji: "po", character: "ぽ", row: ROWS.ALT },

  { romaji: "kya", character: "きゃ", row: ROWS.YOON },
  { romaji: "kyu", character: "きゅ", row: ROWS.YOON },
  { romaji: "kyo", character: "きょ", row: ROWS.YOON },
  { romaji: "sha", character: "しゃ", row: ROWS.YOON },
  { romaji: "shu", character: "しゅ", row: ROWS.YOON },
  { romaji: "sho", character: "しょ", row: ROWS.YOON },
  { romaji: "cha", character: "ちゃ", row: ROWS.YOON },
  { romaji: "chu", character: "ちゅ", row: ROWS.YOON },
  { romaji: "cho", character: "ちょ", row: ROWS.YOON },
  { romaji: "nya", character: "にゃ", row: ROWS.YOON },
  { romaji: "nyu", character: "にゅ", row: ROWS.YOON },
  { romaji: "nyo", character: "にょ", row: ROWS.YOON },
  { romaji: "hya", character: "ひゃ", row: ROWS.YOON },
  { romaji: "hyu", character: "ひゅ", row: ROWS.YOON },
  { romaji: "hyo", character: "ひょ", row: ROWS.YOON },
  { romaji: "mya", character: "みゃ", row: ROWS.YOON },
  { romaji: "myu", character: "みゅ", row: ROWS.YOON },
  { romaji: "myo", character: "みょ", row: ROWS.YOON },
  { romaji: "rya", character: "りゃ", row: ROWS.YOON },
  { romaji: "ryu", character: "りゅ", row: ROWS.YOON },
  { romaji: "ryo", character: "りょ", row: ROWS.YOON },
  { romaji: "gya", character: "ぎゃ", row: ROWS.YOON },
  { romaji: "gyu", character: "ぎゅ", row: ROWS.YOON },
  { romaji: "gyo", character: "ぎょ", row: ROWS.YOON },
  { romaji: "ja", character: "じゃ", row: ROWS.YOON },
  { romaji: "ju", character: "じゅ", row: ROWS.YOON },
  { romaji: "jo", character: "じょ", row: ROWS.YOON },
  { romaji: "bya", character: "びゃ", row: ROWS.YOON },
  { romaji: "byu", character: "びゅ", row: ROWS.YOON },
  { romaji: "byo", character: "びょ", row: ROWS.YOON },
  { romaji: "pya", character: "ぴゃ", row: ROWS.YOON },
  { romaji: "pyu", character: "ぴゅ", row: ROWS.YOON },
  { romaji: "pyo", character: "ぴょ", row: ROWS.YOON }
];
