import ROWS from './rows';

export default [
  { character: 'きゃ', sound: 'kya', romaji: 'kya', row: ROWS.YOON },
  { character: 'きゅ', sound: 'kyu', romaji: 'kyu', row: ROWS.YOON },
  { character: 'きょ', sound: 'kyo', romaji: 'kyo', row: ROWS.YOON },
  { character: 'しゃ', sound: 'sha', romaji: 'sha', row: ROWS.YOON },
  { character: 'しゅ', sound: 'shu', romaji: 'shu', row: ROWS.YOON },
  { character: 'しょ', sound: 'sho', romaji: 'sho', row: ROWS.YOON },
  { character: 'ちゃ', sound: 'cha', romaji: 'cha', row: ROWS.YOON },
  { character: 'ちゅ', sound: 'chu', romaji: 'chu', row: ROWS.YOON },
  { character: 'ちょ', sound: 'cho', romaji: 'cho', row: ROWS.YOON },
  { character: 'にゃ', sound: 'nya', romaji: 'nya', row: ROWS.YOON },
  { character: 'にゅ', sound: 'nyu', romaji: 'nyu', row: ROWS.YOON },
  { character: 'にょ', sound: 'nyo', romaji: 'nyo', row: ROWS.YOON },
  { character: 'ひゃ', sound: 'hya', romaji: 'hya', row: ROWS.YOON },
  { character: 'ひゅ', sound: 'hyu', romaji: 'hyu', row: ROWS.YOON },
  { character: 'ひょ', sound: 'hyo', romaji: 'hyo', row: ROWS.YOON },
  { character: 'みゃ', sound: 'mya', romaji: 'mya', row: ROWS.YOON },
  { character: 'みゅ', sound: 'myu', romaji: 'myu', row: ROWS.YOON },
  { character: 'みょ', sound: 'myo', romaji: 'myo', row: ROWS.YOON },
  { character: 'りゃ', sound: 'rya', romaji: 'rya', row: ROWS.YOON },
  { character: 'りゅ', sound: 'ryu', romaji: 'ryu', row: ROWS.YOON },
  { character: 'りょ', sound: 'ryo', romaji: 'ryo', row: ROWS.YOON },
  { character: 'ぎゃ', sound: 'gya', romaji: 'gya', row: ROWS.YOON },
  { character: 'ぎゅ', sound: 'gyu', romaji: 'gyu', row: ROWS.YOON },
  { character: 'ぎょ', sound: 'gyo', romaji: 'gyo', row: ROWS.YOON },
  { character: 'じゃ', sound: 'ja', romaji: 'ja', row: ROWS.YOON },
  { character: 'じゅ', sound: 'ju', romaji: 'ju', row: ROWS.YOON },
  { character: 'じょ', sound: 'jo', romaji: 'jo', row: ROWS.YOON },
  { character: 'びゃ', sound: 'bya', romaji: 'bya', row: ROWS.YOON },
  { character: 'びゅ', sound: 'byu', romaji: 'byu', row: ROWS.YOON },
  { character: 'びょ', sound: 'byo', romaji: 'byo', row: ROWS.YOON },
  { character: 'ぴゃ', sound: 'pya', romaji: 'pya', row: ROWS.YOON },
  { character: 'ぴゅ', sound: 'pyu', romaji: 'pyu', row: ROWS.YOON },
  { character: 'ぴょ', sound: 'pyo', romaji: 'pyo', row: ROWS.YOON },
];
