import ROWS from './rows';

export default [
  { character: 'キャ', sound: 'kya', romaji: 'kya', row: ROWS.YOON },
  { character: 'キュ', sound: 'kyu', romaji: 'kyu', row: ROWS.YOON },
  { character: 'キョ', sound: 'kyo', romaji: 'kyo', row: ROWS.YOON },
  { character: 'シャ', sound: 'sha', romaji: 'sha', row: ROWS.YOON },
  { character: 'シュ', sound: 'shu', romaji: 'shu', row: ROWS.YOON },
  { character: 'ショ', sound: 'sho', romaji: 'sho', row: ROWS.YOON },
  { character: 'チャ', sound: 'cha', romaji: 'cha', row: ROWS.YOON },
  { character: 'チュ', sound: 'chu', romaji: 'chu', row: ROWS.YOON },
  { character: 'チョ', sound: 'cho', romaji: 'cho', row: ROWS.YOON },
  { character: 'ニャ', sound: 'nya', romaji: 'nya', row: ROWS.YOON },
  { character: 'ニュ', sound: 'nyu', romaji: 'nyu', row: ROWS.YOON },
  { character: 'ニョ', sound: 'nyo', romaji: 'nyo', row: ROWS.YOON },
  { character: 'ヒャ', sound: 'hya', romaji: 'hya', row: ROWS.YOON },
  { character: 'ヒュ', sound: 'hyu', romaji: 'hyu', row: ROWS.YOON },
  { character: 'ヒョ', sound: 'hyo', romaji: 'hyo', row: ROWS.YOON },
  { character: 'ミャ', sound: 'mya', romaji: 'mya', row: ROWS.YOON },
  { character: 'ミュ', sound: 'myu', romaji: 'myu', row: ROWS.YOON },
  { character: 'ミョ', sound: 'myo', romaji: 'myo', row: ROWS.YOON },
  { character: 'リャ', sound: 'rya', romaji: 'rya', row: ROWS.YOON },
  { character: 'リュ', sound: 'ryu', romaji: 'ryu', row: ROWS.YOON },
  { character: 'リョ', sound: 'ryo', romaji: 'ryo', row: ROWS.YOON },
  { character: 'ギャ', sound: 'gya', romaji: 'gya', row: ROWS.YOON },
  { character: 'ギュ', sound: 'gyu', romaji: 'gyu', row: ROWS.YOON },
  { character: 'ギョ', sound: 'gyo', romaji: 'gyo', row: ROWS.YOON },
  { character: 'ジャ', sound: 'ja', romaji: 'ja', row: ROWS.YOON },
  { character: 'ジュ', sound: 'ju', romaji: 'ju', row: ROWS.YOON },
  { character: 'ジョ', sound: 'jo', romaji: 'jo', row: ROWS.YOON },
  { character: 'ビャ', sound: 'bya', romaji: 'bya', row: ROWS.YOON },
  { character: 'ビュ', sound: 'byu', romaji: 'byu', row: ROWS.YOON },
  { character: 'ビョ', sound: 'byo', romaji: 'byo', row: ROWS.YOON },
  { character: 'ピャ', sound: 'pya', romaji: 'pya', row: ROWS.YOON },
  { character: 'ピュ', sound: 'pyu', romaji: 'pyu', row: ROWS.YOON },
  { character: 'ピョ', sound: 'pyo', romaji: 'pyo', row: ROWS.YOON },
];
