import ROWS from "./rows";

export default [
  { sound: "a", character: "ア", row: ROWS.A },
  { sound: "i", character: "イ", row: ROWS.A },
  { sound: "u", character: "ウ", row: ROWS.A },
  { sound: "e", character: "エ", row: ROWS.A },
  { sound: "o", character: "オ", row: ROWS.A },

  { sound: "ka", character: "カ", row: ROWS.KA },
  { sound: "ki", character: "キ", row: ROWS.KA },
  { sound: "ku", character: "ク", row: ROWS.KA },
  { sound: "ke", character: "ケ", row: ROWS.KA },
  { sound: "ko", character: "コ", row: ROWS.KA },

  { sound: "sa", character: "サ", row: ROWS.SA },
  { sound: "shi", character: "シ", row: ROWS.SA },
  { sound: "su", character: "ス", row: ROWS.SA },
  { sound: "se", character: "セ", row: ROWS.SA },
  { sound: "so", character: "ソ", row: ROWS.SA },

  { sound: "ta", character: "タ", row: ROWS.TA },
  { sound: "chi", character: "チ", row: ROWS.TA },
  { sound: "tsu", character: "ツ", row: ROWS.TA },
  { sound: "te", character: "テ", row: ROWS.TA },
  { sound: "to", character: "ト", row: ROWS.TA },

  { sound: "na", character: "ナ", row: ROWS.NA },
  { sound: "ni", character: "ニ", row: ROWS.NA },
  { sound: "nu", character: "ヌ", row: ROWS.NA },
  { sound: "ne", character: "ネ", row: ROWS.NA },
  { sound: "no", character: "ノ", row: ROWS.NA },

  { sound: "ha", character: "ハ", row: ROWS.HA },
  { sound: "hi", character: "ヒ", row: ROWS.HA },
  { sound: "fu", character: "フ", row: ROWS.HA },
  { sound: "he", character: "ヘ", row: ROWS.HA },
  { sound: "ho", character: "ホ", row: ROWS.HA },

  { sound: "ma", character: "マ", row: ROWS.MA },
  { sound: "mi", character: "ミ", row: ROWS.MA },
  { sound: "mu", character: "ム", row: ROWS.MA },
  { sound: "me", character: "メ", row: ROWS.MA },
  { sound: "mo", character: "モ", row: ROWS.MA },

  { sound: "ra", character: "ラ", row: ROWS.RA },
  { sound: "ri", character: "リ", row: ROWS.RA },
  { sound: "ru", character: "ル", row: ROWS.RA },
  { sound: "re", character: "レ", row: ROWS.RA },
  { sound: "ro", character: "ロ", row: ROWS.RA },

  { sound: "ya", character: "ヤ", row: ROWS.YA },
  { sound: "yu", character: "ユ", row: ROWS.YA },
  { sound: "yo", character: "ヨ", row: ROWS.YA },

  { sound: "wa", character: "ワ", row: ROWS.WA },
  { sound: "wo", character: "ヲ", row: ROWS.WA },
  { sound: "n", character: "ン", row: ROWS.WA },

  { sound: "ga", character: "ガ", row: ROWS.ALT },
  { sound: "gi", character: "ギ", row: ROWS.ALT },
  { sound: "gu", character: "グ", row: ROWS.ALT },
  { sound: "ge", character: "ゲ", row: ROWS.ALT },
  { sound: "go", character: "ゴ", row: ROWS.ALT },
  { sound: "za", character: "ザ", row: ROWS.ALT },
  { sound: "ji", character: "ジ", row: ROWS.ALT },
  { sound: "zu", character: "ズ", row: ROWS.ALT },
  { sound: "ze", character: "ゼ", row: ROWS.ALT },
  { sound: "zo", character: "ゾ", row: ROWS.ALT },
  { sound: "da", character: "ダ", row: ROWS.ALT },
  { sound: "ji", character: "ヂ", row: ROWS.ALT },
  { sound: "zu", character: "ヅ", row: ROWS.ALT },
  { sound: "de", character: "デ", row: ROWS.ALT },
  { sound: "do", character: "ド", row: ROWS.ALT },
  { sound: "ba", character: "バ", row: ROWS.ALT },
  { sound: "bi", character: "ビ", row: ROWS.ALT },
  { sound: "bu", character: "ブ", row: ROWS.ALT },
  { sound: "be", character: "ベ", row: ROWS.ALT },
  { sound: "bo", character: "ボ", row: ROWS.ALT },
  { sound: "pa", character: "パ", row: ROWS.ALT },
  { sound: "pi", character: "ピ", row: ROWS.ALT },
  { sound: "pu", character: "プ", row: ROWS.ALT },
  { sound: "pe", character: "ペ", row: ROWS.ALT },
  { sound: "po", character: "ポ", row: ROWS.ALT },

  { sound: "kya", character: "キャ", row: ROWS.YOON },
  { sound: "kyu", character: "キュ", row: ROWS.YOON },
  { sound: "kyo", character: "キョ", row: ROWS.YOON },
  { sound: "sha", character: "シャ", row: ROWS.YOON },
  { sound: "shu", character: "シュ", row: ROWS.YOON },
  { sound: "sho", character: "ショ", row: ROWS.YOON },
  { sound: "cha", character: "チャ", row: ROWS.YOON },
  { sound: "chu", character: "チュ", row: ROWS.YOON },
  { sound: "cho", character: "チョ", row: ROWS.YOON },
  { sound: "nya", character: "ニャ", row: ROWS.YOON },
  { sound: "nyu", character: "ニュ", row: ROWS.YOON },
  { sound: "nyo", character: "ニョ", row: ROWS.YOON },
  { sound: "hya", character: "ヒャ", row: ROWS.YOON },
  { sound: "hyu", character: "ヒュ", row: ROWS.YOON },
  { sound: "hyo", character: "ヒョ", row: ROWS.YOON },
  { sound: "mya", character: "ミャ", row: ROWS.YOON },
  { sound: "myu", character: "ミュ", row: ROWS.YOON },
  { sound: "myo", character: "ミョ", row: ROWS.YOON },
  { sound: "rya", character: "リャ", row: ROWS.YOON },
  { sound: "ryu", character: "リュ", row: ROWS.YOON },
  { sound: "ryo", character: "リョ", row: ROWS.YOON },
  { sound: "gya", character: "ギャ", row: ROWS.YOON },
  { sound: "gyu", character: "ギュ", row: ROWS.YOON },
  { sound: "gyo", character: "ギョ", row: ROWS.YOON },
  { sound: "ja", character: "ジャ", row: ROWS.YOON },
  { sound: "ju", character: "ジュ", row: ROWS.YOON },
  { sound: "jo", character: "ジョ", row: ROWS.YOON },
  { sound: "bya", character: "ビャ", row: ROWS.YOON },
  { sound: "byu", character: "ビュ", row: ROWS.YOON },
  { sound: "byo", character: "ビョ", row: ROWS.YOON },
  { sound: "pya", character: "ピャ", row: ROWS.YOON },
  { sound: "pyu", character: "ピュ", row: ROWS.YOON },
  { sound: "pyo", character: "ピョ", row: ROWS.YOON }
];
